### ISSUE TITLE
getRates() shows one less value than discoverServices()

### ISSUE THREAD

**Issue by Akash-code26** [t3rminus/canada-post#5]
When i check the website for rating , its shows 4 options for Canada to Canada but in the api call for getRates() it shows 3 options , but the discover Services() shows all 4. This happens for Canada to Canada , US and International seem to be working fine.

**Comment by t3rminus** [comment]
Can you provide an example address or postal codes where this is the case?

**Comment by Akash-code26** [comment]
From: M9W7G6 To: H7R4X4 ( Canada to Canada) , length - width - 23cm ,  height -15cm weight- .2kg

Also now I am seeing Us and International showing one value more than what is there in the site. 
US destination code - 28376 , and international country code - IN 

p.s I am really impressed how you have simplified the code so much , you are a genius 👌👌👌

**Comment by Akash-code26** [comment]
Also how do i set it to production environment?

**Comment by t3rminus** [comment]
It will run in a production environment if you set `NODE_ENV=production` or if you pass 
`false` as the 5th argument in the constructor `(userId, password, customer, [lang], [useTestEndpoint])`

I realize the latter option is undocumented, and I'll work on improving the documentation.

I'll look into the bug mentioned above. Thanks for providing some test data.

**Comment by Akash-code26** [comment]
Thanks , but how could it be fetching one less or more? your fetching sites is based on v3 for rates and discover services,but i changed it to v4 , the results still stay the same, is there something wrong with their Api?

**Comment by Akash-code26** [comment]
I tried using the package on the frontend to get dropdwon list of available shipping options , can you please help me with this error?
Access to fetch at 'https://soa-gw.canadapost.ca/rs/ship/price' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by t3rminus** [comment]
@Akash-code26 I'm not able to reproduce the issue you're describing. I'm getting the same 4 results for both entries.

discoverServices
<img width="437" alt="Screen Shot 2020-10-23 at 1 49 40 PM" src="https://user-images.githubusercontent.com/643473/97052985-de7bba80-1536-11eb-8eb7-f61ab7ef75dd.png">

getRates
<img width="432" alt="Screen Shot 2020-10-23 at 1 49 25 PM" src="https://user-images.githubusercontent.com/643473/97052986-df145100-1536-11eb-8b8e-9986ed1e682b.png">

Is there any more information you can give me? Here are the calls I'm making:
```
cpc.discoverServices('M9W7G6', 'CA', 'H7R4X4')
```

```
cpc.getRates({
      parcelCharacteristics: {
        weight: 0.2,
        dimensions: {
          length: 23,
          width: 23,
          height: 15
        }
      },
      originPostalCode: 'M9W7G6',
      destination: {
        domestic: {
          postalCode: 'H7R4X4'
        }
      }
    });
```

**Comment by Akash-code26** [comment]
Yes it's strange, few days back it wasn't showing the options , probably something wrong where the data is being fetched from. Thanks for looking into it.
